#+TITLE: [Android] 在 init.rc 下掛載 UBIFS 檔案系統
#+AUTHOR: coldnew
#+EMAIL:  coldnew.tw@gmail.com
#+DATE:   2014-01-11 10:08:51
#+LANGUAGE: zh_TW
#+URL:    andro
#+OPTIONS: num:nil ^:nil
#+TAGS: android

#+BLOGIT_TYPE: draft

在 Android 的 init.rc 中，可以看到掛載檔案系統使用的 =mount= 命令，而
這命令和我們一般在 Linux 下使用的 mount 命令不同，是個提供給 init 運作的描
述句，你可以在 =system/core/init/builtins.c= 找到他的實現。

在大多數的 Android 設備中，常常可以看到掛載 yaffs2 的描述，卻很少看到 ubifs

#+BEGIN_SRC sh
  mount yaffs2 mtd@system /system
#+END_SRC

為什麼理應效能比較好的 ubifs 卻未被 Android 系統廣泛使用？個人推測有以下原
因

- 1. Android 採用 yaffs2 作為 MTD NAND Flash 檔案系統

- 2. 大多數的 Android 設備 (ex:手機) 都內建有 emmc 作為儲存空間

實際上在我下載到的 AOSP 原始碼中，init 也看不到有支援 ubifs 的影子，那
我們想讓 Android 的 init 掛載 ubifs 要怎麼辦? 這時候只好自己動手了~

* ICS 與 JB 共通的修改部分

Android ICS 以及 JB 在 =system/core/init= 裡面的程式碼，要加上 ubifs 功
能有部分程式碼是相同的，在此將他先列出來。

** 修改 system/core/init/builtins.c

  我們所希望的是可以在 init.rc 增加下面這樣的描述，讓 init 可以掛載 ubifs

  #+BEGIN_SRC sh
    mount ubifs ubi@system /system
  #+END_SRC

  要辦到這項功能，我們必須在 =system/core/init/builtins.c= 裡面加入一
  些程式，讓 init 遇到了 =ubi@= 這樣的語句時，會去使用 ubi_attach 來去掛載
  mtd 設備。

  #+BEGIN_SRC diff
    diff --git a/init/builtins.c b/init/builtins.c
    index b0a97ae..d8066a2 100644
    --- a/init/builtins.c
    +++ b/init/builtins.c
    @@ -325,6 +325,22 @@ int do_mount(int nargs, char **args)
             }

             goto exit_success;
    +    } else if (!strncmp(source, "ubi@", 4)) {
    +        n = ubi_attach_mtd(source + 4);
    +        if (n < 0) {
    +            return -1;
    +        }
    +
    +        sprintf(tmp, "/dev/ubi%d_0", n);
    +
    +        if (wait)
    +            wait_for_file(tmp, COMMAND_RETRY_TIMEOUT);
    +        if (mount(tmp, target, system, flags, options) < 0) {
    +            ubi_detach_dev(n);
    +            return -1;
    +        }
    +
    +        goto exit_success;
         } else if (!strncmp(source, "loop@", 5)) {
             int mode, loop, fd;
             struct loop_info info;

  #+END_SRC

** 修改 system/core/init/util.h

#+BEGIN_SRC diff
  diff --git a/init/util.h b/init/util.h
  index 45905b6..09aa574 100644
  --- a/init/util.h
  +++ b/init/util.h
  @@ -41,4 +41,7 @@ void get_hardware_name(char *hardware, unsigned int *revision);
   void import_kernel_cmdline(int in_qemu, void (*import_kernel_nv)(char *name, int in_qemu));
   int make_dir(const char *path, mode_t mode);
   int restorecon(const char *pathname);
  +
  +int ubi_attach_mtd(const char *name);
  +int ubi_detach_dev(int dev);
   #endif
#+END_SRC

* 讓 Android 4.0.4 (ICS) 支援 ubifs


* 讓 Android 4.2 (JB) 支援 ubifs


* 參考連結

~[1]~ [[http://blog.chinaunix.net/uid-22028680-id-3015767.html][採用 UBIFS 製作 Android 的文件系統]]

~[2]~ [[http://www.cnblogs.com/linucos/p/3279381.html][android 和 ubifs]]
