#+TITLE: 使用 debootstrap 建立完整的 Debian 系統
#+AUTHOR: coldnew
#+EMAIL:  coldnew.tw@gmail.com
#+DATE:   2013-10-28 21:05:24
#+LANGUAGE: zh_TW
#+URL:    f69614
#+OPTIONS: num:nil ^:nil
#+TAGS: debian debootstrap bootstrap
#+TYPE: draft

在製作嵌入式系統的過程中，常常會儘可能精簡整個系統，因此將 gdb、strace
等除錯的好幫手拿掉。如果精簡的 Linux 系統出了問題，要怎進行除錯呢？
=debootstrap + chroot= 是我最常用的組合。

debootstrap 是 Debian 提供用於建立迷你 Debian 系統的方案，使用他可以在你
所指定的目錄下安裝一個基本的 Debian 系統，除了一些配置以外，其內容與
使用 Debian 安裝光碟第一階段安裝的內容基本相同。除此之外，你也可以指定
產生出來的 Debian 架構，使用 debootstrap 產生出 armel、armhf、mips 等不同
的 CPU 架構的 Debian 系統，再透過 qemu chroot 進行訂製。

* 安裝 debootstrap

- Debian / Ubuntu

  #+BEGIN_SRC sh
    sudo apt-get install debootstrap
  #+END_SRC

- Gentoo

  #+BEGIN_SRC sh
    sudo emerge debootstrap
  #+END_SRC

* 建立 x86/amd64 的 Debian 系統

要建立和主系統相同架構下的 Debian 系統，首先我們先創建一個
=rootfs-debian= 目錄。

#+BEGIN_SRC sh
  sudo mkdir /rootfs-debian
#+END_SRC

接著使用下面這行 debootstrap 命令，Debian 就會安裝到 /rootfs-deebian 下了

#+BEGIN_SRC sh
  sudo debootstrap --arch i386 sid /rootfs-debian http://debian.linux.org.tw/debian
#+END_SRC

整個 debootstrap 的命令架構如下

#+BEGIN_SRC sh
  debootstrap --arch <ARCH> <VERSION> <DIRECTORY>  <MIRROR>
#+END_SRC

- ARCH

  ARCH 代表目標系統的 CPU 架構，常用的有 i386、amd64、armel、armhf 等。

- VERSION

  VERSION 代表 Debian 的版本，你可以使用目前的穩定版本 *wheezy* ，或是
  永遠的測試版 *sid* ，當然你也可以選擇更不穩定的 testing，詳細版本名
  稱請見 Debian 官網。

- DIRECTORY

  安裝的目錄，這個根據自己的需求設定即可

- MIRROR

  下載 Debian 套件的伺服器，通常選擇該使用者區域內的服務器，以下為台灣的 Debian Mirror

  http://ftp.tw.debian.org/debian/

* 修改你的 Debian 系統

剛建立好的 Debian Rootfs 還是有一些需要你去修改的檔案，比如說
=/etc/fstab= 、 =/etc/inittab= 等。如果你使用 debootstrap 建立 Debian
rootfs 的目的是進行 chroot，你只需要修改 =/etc/apt/source.list= 即可。

一開始 debootstrap 建立出來的 =/etc/apt/source.list= 是一個空白檔案，你
需要自己去添加自己想要的 debian mirror，debian mirror 取得的方式可以參
考 [[http://debgen.simplylinux.ch/][Debian Source List Generator]] ，以下是我常添加的資訊 (sid)。

#+BEGIN_SRC sh
  deb http://ftp.tw.debian.org/debian unstable main contrib
  deb-src http://ftp.tw.debian.org/debian unstable main contrib
#+END_SRC

* 將你的 Debian 安裝到 USB 隨身碟

如果你使用 debootstrap 的目的，是建立一個輕巧的 Debian 隨身碟，則除了
將剛剛所產生的檔案移到隨身碟下，你同時還要進行以下步驟。

* 建立 ARM 平台的 Debian 系統
* 參考連結

~[1]~ [[http://rediceli.blogspot.tw/2006/08/debootstrapdebian.html][通過 debootstrap 安裝 Debian]]
