#+TITLE: 在 Gentoo Linux 下開發 STM32f4 Discovery 程式
#+AUTHOR: coldnew
#+EMAIL:  coldnew.tw@gmail.com
#+DATE:   2013-12-18 22:10:05
#+LANGUAGE: zh_TW
#+URL:    686_g
#+OPTIONS: num:nil ^:nil
#+TAGS: stm32 stm32f4 gentoo linux

#+BLOGIT_TYPE: draft

在過去，常見的微控器大概就是 8051、AVR、PIC 這幾款 8-bit 微控器，然而，
隨著 ARM 的崛起，也開始越來愈多廠商投入 32-bit ARM 微控器的市場。

更多關於 8-bit MCU 和 32-bit MCU 的資訊，請參考 [[http://tw.myblog.yahoo.com/chamberplus-taiwan/article?mid%3D5340&prev%3D5370&next%3D5336&l%3Da&fid%3D25][意法發佈低成本 32 位元 MCU 產品，攻 8 位元市場]]。

* 建立 ARM 微控器開發環境

身為一個死忠的 Gentoo Linux 使用者，遇到需要新的 toolchain 的時候，自
然就是 =crossdev= 一下了，在 Gentoo Linux 中你可以直接用以下方式建立給
ARM 微控器用的 toolchain。

#+BEGIN_EXAMPLE
  Rosia stm32 # crossdev -s4 -t arm-none-eabi
#+END_EXAMPLE

若有需要建立 GDB，則再加上 =--ex-gdb= 這組參數。

如果你懶得使用 crossdev 編譯 toolchain，則可以到 [[https://launchpad.net/gcc-arm-embedded][GNU Tools for ARM
Embedded Processors]] 下載現成的 toolchain。

除了 toolchain 外，我們亦需要可以在 Linux 下與 STM32 Discovery 開發版溝通
用的程式 [[https://github.com/texane/stlink][stlink]] ，若你是 Gentoo Linux 的使用者，你可以透過
[[https://github.com/coldnew/coldnew-overlay/blob/master/dev-vcs/git-wip/git-wip-0.1.ebuild][coldnew-overlay]] 來安裝 [[https://github.com/texane/stlink][stlink]] ，或是從 GitHub 上下載原始碼自己編譯、安
裝 。

安裝完 [[https://github.com/texane/stlink][stlink]] 後，記得還要安裝 [[http://openocd.sourceforge.net/][OpenOCD]] ，這是一個開源的調適器，可以協
助你更好的除錯你的 STM32 微空器，[[http://openocd.sourceforge.net/][OpenOCD]] 以被各大 Linux 發行版所收錄，使
用你習慣的安裝方式安裝即可。


* 參考連結

~[1]~  [[http://tw.myblog.yahoo.com/chamberplus-taiwan/article?mid%3D5340&prev%3D5370&next%3D5336&l%3Da&fid%3D25][意法發佈低成本 32 位元 MCU 產品，攻 8 位元市場]]

~[2]~ [[http://hackaday.com/2011/10/17/how-to-develop-for-stm32-discovery-boards-using-linux/][How to develop for STM32 discovery boards using linux]]

~[3]~ [[http://descent-incoming.blogspot.tw/2013/04/for-stm32f4discovery-0-linux.html][作業系統之前的程式 for stm32f4discovery (0) - 打造 linux 開發環境]]

~[4]~ [[http://liviube.wordpress.com/2013/04/22/blink-for-stm32f4-discovery-board-on-linux-with-makefile/][Blink for stm32f4-discovery board on Linux with Makefile]]

~[5]~ [[https://github.com/texane/stlink/blob/master/doc/tutorial/tutorial.pdf?raw%3Dtrue][Using STM32 discovery kits with open source tools (PDF)]]

~[6]~ [[http://www.triplespark.net/elec/pdev/arm/stm32.html][Programming STM32 F2, F4 ARMs under Linux: A Tutorial from Scratch]]
